"""Added photo_url to Actor

Revision ID: 64d0c81d4e0e
Revises: 6b9a42428440
Create Date: 2025-03-31 19:05:14.413040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d0c81d4e0e'
down_revision = '6b9a42428440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
