"""Added director, trailer, and actors

Revision ID: 6b9a42428440
Revises: 5b10b3108dd6
Create Date: 2025-03-31 18:53:57.742402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9a42428440'
down_revision = '5b10b3108dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('trailer_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('trailer_url')
        batch_op.drop_column('director')

    # ### end Alembic commands ###
