"""Added director, trailer, and actors

Revision ID: abe44c907590
Revises: 64d0c81d4e0e
Create Date: 2025-03-31 19:33:17.466097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe44c907590'
down_revision = '64d0c81d4e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
